# NOTE: Generated By HttpRunner v3.1.4
# FROM: validate.yml


from rrtv_httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseValidate(HttpRunner):
    config = Config("basic test with httpbin").base_url("http://httpbin.org/") \
        # .db(**{
        # "mysql": "{'host': '10.97.8.67', 'port': '3306', 'user': 'rrtvappuser', 'password': 'c36bad1e12', 'charset': 'utf8','database': 'rrmj2'}"})

    # todo k v形式 支持多数据库
    teststeps = [
        Step(
            RunRequest("validate response with json path")
            .get("/get")
            .with_params(**{"a": 1, "b": 2})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.args.a", "1")
            .assert_equal("body.args.b", "2")
        ),
        Step(
            RunRequest("validate response with python script")
                .with_variables(**{"test2": 1, "test": "$test2"})
                .setup_exec("sql:select * from t_user_appeal_record limit 1;")
                .setup_exec("cmd:ls -al")
                .get("/get")
                .with_params(**{"a": 1, "b": 2})
                .teardown_exec(f"sql:update t_adolescent_model set status=true WHERE user_id ='$args';")
                .extract()
                .with_jmespath("body.args.a", "args")
                .with_jmespath("sql:select * from t_user_appeal_record limit $test2;['ID']", "sql1")
                .with_extra("sql:select * from t_user_appeal_record limit $test2;['aaa']", "sql1")
                .validate()
                .assert_string_equals("$test$test", "$sql1")
        ),
    ]


if __name__ == "__main__":
    TestCaseValidate().test_start()
